### ISSUE TITLE
How to run on node for end-to-end test

### ISSUE THREAD

**Issue by yormi** [reactjs/react-router-redux#322]
Hey fellows !

I'm not sure if I should post here or on Jsdom project but when I'm trying to execute end-to-end tests with Node and Jsdom, I get this error:

```
/home/guillaume/Documents/Random_Projects/cookies/client/node_modules/jsdom/lib/jsdom/living/window/Location-impl.js:219
      throw new DOMException(DOMException.SYNTAX_ERR, `Could not resolve the given string "${url}" relative to the ` +
      ^
SyntaxError
    at LocationImpl.replace (/home/guillaume/Documents/Random_Projects/cookies/client/node_modules/jsdom/lib/jsdom/living/window/Location-impl.js:219:13)
    at Location.replace (/home/guillaume/Documents/Random_Projects/cookies/client/node_modules/jsdom/lib/jsdom/living/generated/Location.js:39:53)
    at Object.replaceHashPath (/home/guillaume/Documents/Random_Projects/cookies/client/node_modules/history/lib/DOMUtils.js:37:19)
    at ensureSlash (/home/guillaume/Documents/Random_Projects/cookies/client/node_modules/history/lib/createHashHistory.js:40:13)
    at startHashChangeListener (/home/guillaume/Documents/Random_Projects/cookies/client/node_modules/history/lib/createHashHistory.js:103:5)
    at Object.listen (/home/guillaume/Documents/Random_Projects/cookies/client/node_modules/history/lib/createHashHistory.js:167:57)
    at Object.listen (/home/guillaume/Documents/Random_Projects/cookies/client/node_modules/history/lib/useBasename.js:75:22)
    at Object.listen (/home/guillaume/Documents/Random_Projects/cookies/client/node_modules/history/lib/useQueries.js:108:22)
    at syncHistoryWithStore (/home/guillaume/Documents/Random_Projects/cookies/client/node_modules/react-router-redux/lib/sync.js:102:36)
    at Object.<anonymous> (test.js:20:17)
```

Here's the code (mostly taken from the example in the readme):
```
'use strict'

import './setup_fake_dom'
import React from 'react'
import { renderIntoDocument } from 'react-addons-test-utils'
import { createStore, combineReducers } from 'redux'
import { Provider } from 'react-redux'
import { Router, Route, hashHistory } from 'react-router'
import { syncHistoryWithStore, routerReducer } from 'react-router-redux'

// Add the reducer to your store on the `routing` key
const store = createStore(
  combineReducers({
    app: (state) => ({ tate: 'banane' }),
    routing: routerReducer
  })
)

// Create an enhanced history that syncs navigation events with the store
const history = syncHistoryWithStore(hashHistory, store)

class App extends React.Component {
  render () {
    return <p>Olé</p>
  }
}

renderIntoDocument(
  <Provider store={store}>
    { /* Tell the Router to use our enhanced history */ }
    <Router history={history}>
      <Route path='/' component={App} />
    </Router>
  </Provider>,
  document.getElementById('root')
)
```
```
// setup_fake_dom

'use strict'

import jsdom from 'jsdom'

const doc = jsdom.jsdom('<!doctype html><html><body></body></html>')
const win = doc.defaultView

global.document = doc
global.window = win

Object.keys(window).forEach((key) => {
  if (!(key in global)) {
    global[key] = window[key]
  }
})
```
Do you have an idea of a solution ?

Thanks :)

**Comment by yormi** [comment]
Found the answer here: https://github.com/tmpvar/jsdom/issues/1378

I basically need to change this line:
`const doc = jsdom.jsdom('<!doctype html><html><body></body></html>')`
by this one:
`global.document = jsdom('<!doctype html><html><body></body></html>', {
  url: 'http://localhost'
})`

I would like to understand all that Jsdom stuff but I'm a bit intimidated by the readme :P

Closing.
