### ISSUE TITLE
Cannot run gulp

### ISSUE THREAD

**Issue by salex772** [reactjs/react-router-redux#390]
gulp

I get this:

```
10:49:23] Starting 'serve:api'...
[10:49:24] 'serve:api' errored after 7 ms
[10:49:24] Error: 1
    at formatError (C:\Users\salex\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:169:10)
    at Gulp.<anonymous> (C:\Users\salex\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:195:15)
    at emitOne (events.js:90:13)
    at Gulp.emit (events.js:182:7)
    at Gulp.Orchestrator._emitTaskDone (C:\Users\salex\workspace\CSS-Tricks-React-Series\guide-3-redux\node_modules\orchestrator\index.js:264:8)
    at C:\Users\salex\workspace\CSS-Tricks-React-Series\guide-3-redux\node_modules\orchestrator\index.js:275:23
    at finish (C:\Users\salex\workspace\CSS-Tricks-React-Series\guide-3-redux\node_modules\orchestrator\lib\runTask.js:21:8)
    at ChildProcess.cb (C:\Users\salex\workspace\CSS-Tricks-React-Series\guide-3-redux\node_modules\orchestrator\lib\runTask.js:29:3)
    at emitTwo (events.js:105:20)
    at ChildProcess.emit (events.js:185:7)
```

**Comment by salex772** [comment]
Posted to here by mistake
